name: philips-sdk-py37
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2026.5.14
  - certifi=2022.12.7
  - freetype=2.14.1
  - giflib=5.2.2
  - intel-openmp=2021.4.0
  - jpeg=9f
  - lerc=4.1.0
  - libdeflate=1.22
  - libpng=1.6.56
  - libtiff=4.5.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1w
  - pillow=9.4.0
  - python=3.7.9
  - six=1.16.0
  - sqlite=3.51.2
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wincertstore=0.2
  - xz=5.8.2
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - eglrendercontext==5.1.0
      - gles2renderbackend==5.1.0
      - gles3renderbackend==5.1.0
      - openphi==2.1.0
      - pip==24.0
      - pixelengine==5.1.0
      - setuptools==68.0.0
      - softwarerenderbackend==5.1.0
      - softwarerendercontext==5.1.0
      - wheel==0.42.0
