"""Scope intake specification to the supplied AI server; hospital PC is a peer only."""
from pathlib import Path

path=Path(__file__).with_name('build_equipment_specification.py')
source=path.read_text(encoding='utf-8')
source=source.replace('MeDIAuto_PDL1_Equipment_Specification_Network_v01.docx','MeDIAuto_PDL1_Server_Specification_Network_v02.docx').replace('v0.1','v0.2')
source=source.replace("('사용자 단말','익명화 작업용 PC에서 슬라이드 처리·업로드 및 웹 브라우저를 통한 결과 확인. 해당 PC의 신규 반입 여부는 설치 계획 수립 시 확인'),\n",'')
source=source.replace("('익명화 작업용 PC','익명화 프로그램 실행, 처리 결과 검토, 검토된 슬라이드 업로드, 브라우저 기반 결과 확인'),\n",'')
source=source.replace('익명화 작업용 PC와 로컬 AI 서버 직접 연결. AI 서버는 병원망에 연결하지 않음','병원 사용자 단말과 반입 로컬 AI 서버 직접 연결. AI 서버는 병원망에 연결하지 않음')
source=source.replace('MeDIAuto AI를 설치할 로컬 서버. 장비 형태·모델·수량은 선정 후 확정','MeDIAuto AI 로컬 서버 및 연결 부속품. 병원 기존 PC는 반입 장비와 사양 기재 대상에서 제외')
source=source.replace('하드웨어 사양 및 물리 규격','반입 AI 서버 하드웨어 사양 및 물리 규격')
source=source.replace("table(['익명화 작업용 PC','직접 연결','로컬 AI 서버']", "table(['병원 사용자 단말','직접 연결','반입 로컬 AI 서버']")
source=source.replace('계획 구성 / 직접 연결의 물리 방식·IP·포트는 설치 시 확정','병원 사용자 단말은 연결 상대를 표시한 것이며 반입 장비·사양 기재 대상이 아님')
source=source.replace('슬라이드 익명화·검증\\n검토된 처리본 선택\\n웹 브라우저 접속','병원 기존 PC 이용\\n익명화된 슬라이드 업로드\\n브라우저로 영상·결과 확인')
source=source.replace('원본·환자 대응표:\\n병원 지정 보호 위치에 관리','기존 PC 사양은 기재하지 않음\\n장비 관리: 병원')
source=source.replace('PC와 서버 직접 연결로 계획. 연결 매체·포트 규격·속도는 선정 후 확정','병원 사용자 단말과 AI 서버 직접 연결. 연결 매체·규격·속도는 서버 및 부속품 선정 후 확정')
source=source.replace('기능 범위: 슬라이드 익명화·검증, 영상 열람, PD-L1 AI 분석 결과 이용','반입 서버 기능: 익명화된 슬라이드 등록, 영상 열람, PD-L1 분석 및 결과 제공')
source=source.replace('선정 후 확정 — 제품·에디션·버전·사용권','서버 운영체제 설치. 제품·에디션·버전·사용권은 설치 구성 확정 시 기재')
source=source.replace('선정 후 확정 — GPU 드라이버·실행 환경·DB·웹 서비스 및 필요한 구성요소','GPU 드라이버·AI 실행 환경·DB·웹 서비스를 서버에 구성. 실제 구성요소 및 버전은 최종 배포 구성으로 기록')
source=source.replace('최종 설치 시 확정 — 익명화 프로그램·MeDIAuto AI 배포 버전 및 PD-L1 모델 식별정보 기록','MeDIAuto AI의 영상 뷰어·PD-L1 기능 제공. 최종 설치 시 서버 배포 버전 및 PD-L1 모델 식별정보 기록')
source=source.replace('실제 사용할 슬라이드 형식으로 익명화·등록·열람·분석 시험. Philips 사용 시 SDK 실행 환경 및 사용권 확인','익명화된 연구용 슬라이드로 등록·열람·PD-L1 분석 시험. Philips 파일 사용 시 서버 SDK 환경 및 사용권 확인')
source=source.replace('PC와 서버의 저장 위치·권한·전송/저장 보호·로그·백업·보존 및 파기 방법을 설치 시 확정','서버에 등록 영상·PD-L1 결과·로그를 보관. 실제 저장 경로·접근권한·전송/저장 보호·백업·보존/파기 방법은 설치 시 기록')
source=source.replace('승인된 시험 파일로 익명화 → 업로드 → 뷰어 → PD-L1 결과 확인','검토된 익명화 시험 파일로 서버 업로드 → 뷰어 → PD-L1 결과 확인')
source=source.replace('본 구성도는 운영 계획을 나타냅니다. 실제 연결·차단·서비스 접속 시험 결과는 설치 완료 후 기록합니다.','병원 단말의 CPU·메모리·OS 등 사양은 본 문서에 포함하지 않습니다. 실제 연결·차단·서비스 접속 시험 결과는 설치 완료 후 기록합니다.')
exec(compile(source,str(path),'exec'))
